# These are supported funding model platforms

# github: [ardondon]
# patreon: smarthub
# open_collective: smarthub
# ko_fi: smarthub
# tidelift: npm/smarthub
# community_bridge: smarthub
# liberapay: smarthub
# issuehunt: ardondon
# otechie: ardondon
# lfx_crowdfunding: smarthub
# custom: ['https://smarthub.io/donate']

# Uncomment and configure the platforms you want to use
# For now, this is a template - replace with actual funding links when available
